# Generated by Django 4.0.4 on 2023-01-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_api', '0003_alter_music_artist_alter_music_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='song',
            field=models.FileField(blank=True, default=None, null=True, upload_to='music'),
        ),
    ]
