# Generated by Django 4.0.4 on 2023-01-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_api', '0004_music_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='song',
            field=models.FileField(default='Some music', upload_to='music'),
        ),
    ]
